FROM mysql:latest

LABEL maintainer="vincent_fillon@hotmail.com"
# Certains utilisent: "MAINTAINER Vincent Fillon <vincent_fillon@hotmail.com>" mais la commande est Deprecated depuis 2017.

ENV MYSQL_ROOT_PASSWORD medic
ENV MYSQL_DATABASE medicaments
ENV MYSQL_USERS vincent
ENV MYSQL_PASSWORD medic

ADD mysql_charset.cnf /etc/mysql/conf.d/mysql_charset.cnf
ADD medicaments.sql /docker-entrypoint-initdb.d

EXPOSE 3307
